server:
  port: 8080

spring:
  datasource:
    name: mysql_test
#    type: com.alibaba.druid.pool.DruidDataSource    #多数据源配置 将这个去掉
    master: #jdbcurl  默认使用hikaripool作为数据库连接池
      jdbcurl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

    slave:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

    read: get,select,count,list,query,find
    writer: add,create,update,delete,remove,insert
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filter: stat
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: 123456
      #配置初始化大小/最大/最小
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#该配置节点为独立的节点   不要放在spring下
mybatis:
  mapper-locations: classpath:mappers/*.xml  #对应mappers.xml映射文件
  type-aliases-package: com.example.springbootmybatisdemo.entity  #对应实体类路径

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
